# Generated by Django 5.1.5 on 2025-02-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeudeplateau',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
