# Generated by Django 5.1.5 on 2025-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0002_jeudeplateau_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cd',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
