# Generated by Django 5.1.5 on 2025-02-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0003_remove_jeudeplateau_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
