# Generated by Django 5.1.5 on 2025-02-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0004_cd_date_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bibliothecaire.membre'),
        ),
    ]
