# Generated by Django 5.1.5 on 2025-02-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0005_cd_emprunteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bibliothecaire.membre'),
        ),
        migrations.AddField(
            model_name='livre',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bibliothecaire.membre'),
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
