# Generated by Django 5.1.5 on 2025-02-05 10:21

import app_bibliothecaire.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0006_dvd_date_emprunt_dvd_emprunteur_livre_date_emprunt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='date_retour',
            field=models.DateField(blank=True, default=app_bibliothecaire.models.date_retour_defaut, null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='date_retour',
            field=models.DateField(blank=True, default=app_bibliothecaire.models.date_retour_defaut, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='date_retour',
            field=models.DateField(blank=True, default=app_bibliothecaire.models.date_retour_defaut, null=True),
        ),
    ]
