# Generated by Django 5.1.5 on 2025-02-05 11:09

import app_bibliothecaire.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0007_cd_date_retour_dvd_date_retour_livre_date_retour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='date_retour',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='date_retour',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_retour',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('livre', 'Livre'), ('dvd', 'DVD'), ('cd', 'CD')], max_length=10)),
                ('media_id', models.PositiveIntegerField()),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(blank=True, default=app_bibliothecaire.models.date_retour_defaut, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bibliothecaire.membre')),
            ],
        ),
    ]
